main:
  - name: Links
    identifier: support
    weight: 100
    url: https://github.com/stardoom/exobrain
    params:
      header: Links.
      icon:
        vendor: font-awesome-solid
        name: shuttle-space

  - name: GitHub
    parent: support
    url: https://github.com/stardoom4/exobrain
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.
